# Generated by Django 3.1.14 on 2022-05-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsite',
            name='firstName',
            field=models.CharField(default='Anonymous', max_length=64),
        ),
        migrations.AddField(
            model_name='docsite',
            name='lastName',
            field=models.CharField(default='', max_length=64),
        ),
    ]
