# Generated by Django 3.1.14 on 2022-05-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0002_auto_20220525_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='docsite',
            new_name='Testimonial',
        ),
    ]
