# Generated by Django 3.1.14 on 2022-06-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0004_formdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
