# Generated by Django 3.1.14 on 2022-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0005_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('companyName', models.CharField(max_length=100)),
                ('companyType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
