# Generated by Django 3.1.14 on 2022-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0006_auto_20220627_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=100)),
                ('techstack', models.CharField(max_length=100)),
                ('location', models.EmailField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('qualification1', models.CharField(max_length=100)),
                ('qualification2', models.CharField(max_length=100)),
            ],
        ),
    ]
