# Generated by Django 3.1.14 on 2022-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0007_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careers',
            name='qualification1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='careers',
            name='qualification2',
            field=models.CharField(max_length=1000),
        ),
    ]
