# Generated by Django 3.1.14 on 2022-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSite', '0003_auto_20220525_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='formData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=64)),
            ],
        ),
    ]
